version: "3.5"
services:
  db:
    container_name: financas-db
    image: postgres
    environment:
      POSTGRES_DB: financas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    #apenas reinicia caso o conatiner não seja interropido/parado
    restart: unless-stopped
  web:
    container_name: financas-app
    image: financas_api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://financas-db:5432/financas_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    ports:
      - 8181:8080